FROM starefossen/ruby-node:2-8

WORKDIR /app

COPY Gemfile* ./
RUN bundle install

COPY package.json .
RUN yarn install

COPY . .

ARG ITUNES_CONNECT_USERNAME
ARG ITUNES_CONNECT_PASSWORD
ARG SLACK_BOT_API_TOKEN
ARG SLACK_CHANNEL
ARG APP_BUNDLE_ID

ENV ITUNES_CONNECT_USERNAME=$ITUNES_CONNECT_USERNAME
ENV ITUNES_CONNECT_PASSWORD=$ITUNES_CONNECT_PASSWORD
ENV SLACK_BOT_API_TOKEN=$SLACK_BOT_API_TOKEN
ENV SLACK_CHANNEL=$SLACK_CHANNEL
ENV APP_BUNDLE_ID=$APP_BUNDLE_ID

CMD node poll-itc.js
